-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       clangd = {
--         filetypes = { "c", "cpp", "objc", "objcpp", "cuda" }, -- 显式排除 proto
--       },
--     },
--   },
-- }
